### ISSUE TITLE
The ESP32 Basic Core IoT Development Kit is EOL

### ISSUE THREAD

**Issue by miningdave** [kkdao/micro-blockclock#1]
The linked m5stack is EOL: https://shop.m5stack.com/products/basic-core-iot-development-kit?variant=16804801937498
Will the clock work with the replacement?
https://shop.m5stack.com/collections/stack-series/products/m5stack-core2-esp32-iot-development-kit

**Comment by kkdao** [comment]
The beauty of DIY is you can source from other distributors that carry the basic Core device, and not just the Core2 like the m5stack website. 

I don't know your location so I can't recommend any suppliers, but if you search that basic model type you should see results from various suppliers. Some common ones are Digikey, Mouser, Aliexpress, etc.

**Comment by miningdave** [comment]
Did not know if any of the other hardware variations (i.e touchscreen, auth chip)  would cause any other issues. I don't know a lot about the device and did not want to assume anything.

**Comment by kkdao** [comment]
Yes the Core2 version might cause issues, so that is why I was sharing info for acquiring the basic version.
